### ISSUE TITLE
Tabs and labels overlapping interior of model...

### ISSUE THREAD

**Issue by manthrax** [addam/Export-Paper-Model-from-Blender#58] opened 2018-06-16 22:48 UTC
I suggest separating the tab and label exporting code into a separate pass that happens before the main geometry, so that the main geometry is drawn on top?

![image](https://user-images.githubusercontent.com/350247/41502995-b421075a-717c-11e8-82ad-b07874f9d786.png)

**Comment by addam** [comment] 2018-06-20 20:42
This is a duplicate of #46.

**Closed by addam** 2018-06-20 20:42 UTC
